config/routes.rb
Mpf::Application.routes.draw do

  secure_protocol = "https"
  if (Rails.env.development? or Rails.env.test?)
    secure_protocol = "http"
  end  

  resources :mobile_services, :only => [:index, :show]
  resources :service_packages, :only => [:index, :show]

  # match "/auth/ldap/callback" => "admin/user_sessions#create", :constraints => { :protocol => secure_protocol }
  # phusion passenger has issues matching a route with a protocol constraint, so using below instead of above
  match "/auth/ldap/callback" => "admin/user_sessions#create"
  match "/auth/failure" => redirect("/admin/login"), :notice => "login failed"
  
  namespace "admin" do
    get "pages/home"
    get "pages/help"

    resources :mobile_services
    resources :service_packages
    resources :package_memberships, :only => [:create, :update, :destroy]
    resources :users

    match "login" => "user_sessions#new", :as => :login
    match "logout" => "user_sessions#destroy", :as => :logout

    root :to => 'pages#home'
    match "/:unknown" => redirect('/admin/pages/home')
  end

  # NOTE: this has to go after all the namespace definitions or else the name space roots will match this route
  match "/:urltitle" => "adaptive#reroute", :as => :urltitle, :via=>:get
  match "/force/:urltitle" => "adaptive#reroute", :as => :urltitle, :via=>:get

  #root :to => 'service_packages', :action=>'show', :id=>'home'

end

app/models/mobile_service.rb
require 'unique_urltitle_validator'
    
class MobileService < ActiveRecord::Base
  
  attr_accessor :items
  
  validates :title, :presence => true,
                    :length => { :minimum => 1 }, 
                    #:uniqueness => true, # no uniqueness constraint on title - need dupes to support app recs for android and ios
                    :format => { :with => /[A-Za-z0-9\-\'\"\+\.\!\?\@\$\#\%\&\=\,\: ]+/ }

  validates :urltitle,  :presence => true,
                        :length => { :minimum => 1, :maximum => 32 }, 
                        :uniqueness => true,
                        :format => { :with => /[A-Za-z0-9\-\_]+/ },
                        :unique_urltitle => true

  validates :url,   :presence => true,
                    :length => { :minimum => 1 }, 
                    :uniqueness => true
  
  has_many :package_memberships,  :dependent => :destroy, :as => :package_item # contained in

  has_attached_file :icon,
    :path => ":rails_root/public/data/:attachment_:class/:id/:style_:basename.:extension",
    :url => "/data/:attachment_:class/:id/:style_:basename.:extension",
    :styles => {
                :base     => "57x57#",
                :x2       => "114x114#",
                :small16  => "16x16#",
                :small    => "29x29#",
                :small50  => "50x50#",
                :x2small  => "58x58#",
                :px72     => "72x72#"
                }
    
end

app/controllers/admin/mobile_services_controller.rb
class Admin::MobileServicesController < Admin::AdminController

  @@page_title_base = "Admin : Service"

  def index
    @page_title = @@page_title_base+"s"
    @mobile_services = MobileService.all
  end


  def show
    @mobile_service = MobileService.find(params[:id])
    @page_title = @@page_title_base+" : "+@mobile_service.title
  end


  def new
    @mobile_service = MobileService.new
    @page_title = @@page_title_base+" : New"
  end


  def edit
    @mobile_service = MobileService.find(params[:id])
    @packages_not_in = ServicePackage.all - (@mobile_service.package_memberships.collect {|pm| pm.service_package} )
    @page_title = @@page_title_base+" : Edit "+@mobile_service.title
  end


  def create
    @mobile_service = MobileService.new(params[:mobile_service])
    if @mobile_service.save
      redirect_to(admin_mobile_service_url(@mobile_service), :notice => 'Service was successfully created.')
    else
      render "new"
    end
  end


  def update
    @mobile_service = MobileService.find(params[:id])
    if @mobile_service.update_attributes(params[:mobile_service])
      redirect_to(admin_mobile_service_url(@mobile_service), :notice => 'Service was successfully updated.')
    else
      render "edit"
    end
  end


  def destroy
    @mobile_service = MobileService.find(params[:id])
    @mobile_service.destroy
    redirect_to(admin_mobile_services_url)
  end
  
end

app/controllers/mobile_services_controller.rb
class MobileServicesController < ApplicationController

  def index
    @mobile_services = MobileService.where(:is_live=>true,:is_restricted=>false)
    @page_title = "Services"
  end


  def show
    if (params[:id].match /\A\d+\Z/)
      @mobile_service = MobileService.find(params[:id])
    else
      @mobile_service = MobileService.find_by_urltitle(params[:id])
    end

    if ((@mobile_service.is_live) && (! @mobile_service.is_restricted))

      if (@mobile_service.service_type =~ /native|remote/)
        redirect_to @mobile_service.url
        return
      end
    else
      redirect_to :controller=>"mobile_services",:action=>"index"
    end
  end


end

app/helpers/mobile_services_helper.rb
module MobileServicesHelper
end

app/views/admin/mobile_services/_form.html.erb
<%= form_for(@mobile_service) do |f| %>
  <% if @mobile_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mobile_service.errors.count, "error") %> prohibited this mobile_service from being saved:</h2>

      <ul>
      <% @mobile_service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :icon %><br />
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :is_live %><br />
    <%= f.check_box :is_live %>
  </div>
  <div class="field">
    <%= f.label :is_restricted %><br />
    <%= f.check_box :is_restricted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/mobile_services/_form_contents.html.erb
  <% if @mobile_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mobile_service.errors.count, "error") %> prohibited this mobile_service from being saved:</h2>

      <ul>
      <% @mobile_service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <div class="form_input"><%= f.text_field :title %></div>
  </div>
  <div class="field">
    <%= f.label :urltitle %>
    <div class="form_input">http://<%=@servername%>/<%= f.text_field :urltitle %></div>
  </div>
  <div class="field">
    <%= f.label 'Icon' %>
    <div class="form_input"><%= f.file_field :icon, :class=>"icon_input" %><% if @mobile_service.icon.exists? then %>
      <%= image_tag @mobile_service.icon.url(:small), :class=>"icon_view" %>
    <% end %></div>
  </div>
  <div class="field">
    <%= f.label :description %>
    <div class="form_input"><%= f.text_area :description, :rows => 4 %></div>
  </div>

  <div class="field">
    <%= f.label :url %>
    <div class="form_input"><%= f.text_field :url %></div>
  </div>

  <div class="field">
    <%= f.label :full_site_url %>
    <div class="form_input"><%= f.text_field :full_site_url %> <span class="commentary">(this is optional - it is used to generate a link to a full / desktop page that corresponds to this item)</span></div>
  </div>
  
  <div class="field">
    <%= f.label :service_type %>
    <div class="form_input"><%= f.select(:service_type, options_for_select(get_service_types_options_array,(@mobile_service.service_type? ? @mobile_service.service_type : "embedded")))%></div>
  </div>
  
  <div class="field">
    <%= f.label :is_live %>
    <div class="form_input"><%= f.check_box :is_live %></div>
  </div>
  <div class="field">
    <%= f.label :is_restricted %>
    <div class="form_input"><%= f.check_box :is_restricted %></div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/admin/mobile_services/edit.html.erb
<script type="text/javascript">
$(document).ready(function(){

  $(".in_package  .add_button").hide();
  $(".out_of_package  .remove_button").hide();

  var no_package_item = "<li>This service is not in any packages.</li>";

  $(".add_button").click(
    function()
      {
        var cached_this = this;
        //alert("add");

        $.ajax(
          {
            url: '<%=admin_package_memberships_path%>',
            type: 'POST',
            data: {action: 'create',
                   item: <%=@mobile_service.id.to_s%>, 
                   package: $(this).parent().parent().attr("for"),
                   item_type: '<%=@mobile_service.class.to_s%>'},
            success:function(data, textStatus) 
              {
                //alert("data is "+data); //DEBUG
                $(".package_lister ul li:contains('This service is not in any packages.')").remove();
                $(cached_this).parent().find(".button").toggle();
                $(cached_this).parent().removeClass("out_of_package");
                $(cached_this).parent().addClass("in_package");
                $(cached_this).parent().parent().attr("as",data);
              },
            error:function(request, textStatus, errorThrown)
              {
                alert("could not put this service in that package: "+errorThrown);
              }
          });
      });

  $(".remove_button").click(
    function()
      {
        var cached_this = this;
        //alert("remove");

        $.ajax(
          {
            url: '/admin/package_memberships/'+$(cached_this).parent().parent().attr("as"),
            type: 'DELETE',
            data: {action: 'destroy',
                   id: $(this).parent().parent().attr("as")},
            success:function(data, textStatus) 
              {
                $(cached_this).parent().parent().attr("as","0");
                $(cached_this).parent().find(".button").toggle();
                $(cached_this).parent().removeClass("in_package");
                $(cached_this).parent().addClass("out_of_package");
                if ($(".package_lister ul li .in_package").length == 0) { 
                  $(".package_lister ul").prepend(no_package_item);
                }          
              },
            error:function(request, textStatus, errorThrown)
              {
                alert("could not remove this service from that package: "+errorThrown);
              }
          });
      });
      
});
</script>

<div class="left_col service_info">
<%= form_for(@mobile_service,
             :html => { :multipart => true },
             :url => admin_mobile_service_path(@mobile_service) ) do |f| %>
<%= render 'form_contents', :f => f %>
<% end %>
</div>

<div class="right_col">
  <div class="package_lister">
    <h2>Package Membership</h2>
    <ul class="package_list">
<%if @mobile_service.package_memberships.empty?%>
      <li>This service is not in any packages.</li>
<%else%>
  <%@mobile_service.package_memberships.each do |pm|
      sp = pm.service_package %>
      <%=admin_service_package_item(sp,pm, "<div class=\"button_container in_package\">"+add_button+remove_button+"</div><div class=\"package_container\">","</div>")%>
  <%end%>
<%end%>
<%@packages_not_in.each do |sp|%>
      <%=admin_service_package_item(sp, nil, "<div class=\"button_container out_of_package\">"+add_button+remove_button+"</div><div class=\"package_container\">","</div>")%>
<%end%>
    </ul>
  </div>
</div>

<br clear="all"/>

<%= link_to 'Show', admin_mobile_service_path(@mobile_service) %> |
<%= link_to 'All Services', admin_mobile_services_path %>

app/views/admin/mobile_services/index.html.erb
<h3><%= link_to 'Make a new Service', new_admin_mobile_service_path %></h3>

<table  class="index_lister">

<% @mobile_services.each do |mobile_service| 
  url_class="type_unknown"
  if (@service_types.include?(mobile_service.service_type))
    url_class="type_"+mobile_service.service_type
  end
  %>
  <tr>
    <td<%= ((mobile_service.is_live)?' title="live"':' class="not_live" title="not live"').html_safe%>><%= (mobile_service.is_live)?(image_tag "admin/live.png"):(image_tag "admin/not_live.png")%></td>
    <td><% if mobile_service.icon.exists? then %>
      <%= image_tag mobile_service.icon.url(:base) %>
    <% else %>
      NO ICON! (should never be seen!)
    <% end %></td>
    <td><%= mobile_service.title %></td>
    <td class="first_action" title="see details"><%= link_to (image_tag "admin/information.png"), admin_mobile_service_path(mobile_service) %></td>
    <td title="edit"><%= link_to (image_tag "admin/pencil.png"), edit_admin_mobile_service_path(mobile_service) %></td>
    <td title="delete"><%= link_to (image_tag "admin/delete.png"), admin_mobile_service_path(mobile_service), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/admin/mobile_services/new.html.erb
<%= form_for(@mobile_service,
             :html => { :multipart => true },
             :url => admin_mobile_services_path ) do |f| %>
<%= render 'form_contents', :f => f %>
<% end %>

<%= link_to 'Cancel', admin_mobile_services_path %>

app/views/admin/mobile_services/show.html.erb
<p id="notice"><%= notice %></p>

<div class="left_col">

  <div class="field">
    <label><b>Title:</b></label>
    <div class="value"><%= @mobile_service.title %></div>
  </div>

  <div class="field">
    <label><b>URL Title:</b></label>
    <div class="value"><%= @mobile_service.urltitle %></div>
  </div>
  <div class="field">
    <label><b>Icon:</b></label>
    <div class="value"><% if @mobile_service.icon.exists? then %>
      <%= image_tag @mobile_service.icon.url(:small) %>
    <% else %>
      NO ICON! (should never be seen!)
    <% end %></div>
  </div>  
  <div class="field">
    <label><b>Description:</b></label>
    <div class="value"><%= @mobile_service.description %></div>
  </div>
  <div class="field">
    <label><b>URL:</b></label>
    <div class="value"><%= @mobile_service.url %></div>
  </div>
  <div class="field">
    <label><b>Full Site URL:</b></label>
    <div class="value"><%= @mobile_service.full_site_url %></div>
  </div>
  <div class="field">
    <label><b>Type:</b></label>
    <div class="value"><%= @mobile_service.service_type %></div>
  </div>
  <div class="field">
    <label><b>Is live:</b></label>
    <div class="value"><%= @mobile_service.is_live %></div>
  </div>
  <div class="field">
    <label><b>Is restricted:</b></label>
    <div class="value"><%= @mobile_service.is_restricted %></div>
  </div>


</div>

<div class="right_col">
<div class="service_package_list">
 <b>In Packages:</b>
 <ul>
 <% if (@mobile_service.package_memberships.empty?) %>
  <li>None</li>
 <% else %>
     <% @mobile_service.package_memberships.each do |pm| %>
       <% sp = pm.service_package %>
   <li><%= link_to ((image_tag sp.icon.url(:base)) + sp.title),
                   admin_service_package_path(sp) %></li>
     <% end
   end %>
 </ul>
</div>
</div>

<br clear="all"/>
<%= link_to 'Edit', edit_admin_mobile_service_path(@mobile_service) %> |
<%= link_to 'All Services', admin_mobile_services_path %>