config/routes.rb
Mpf::Application.routes.draw do

  secure_protocol = "https"
  if (Rails.env.development? or Rails.env.test?)
    secure_protocol = "http"
  end  

  resources :mobile_services, :only => [:index, :show]
  resources :service_packages, :only => [:index, :show]

  # match "/auth/ldap/callback" => "admin/user_sessions#create", :constraints => { :protocol => secure_protocol }
  # phusion passenger has issues matching a route with a protocol constraint, so using below instead of above
  match "/auth/ldap/callback" => "admin/user_sessions#create"
  match "/auth/failure" => redirect("/admin/login"), :notice => "login failed"
  
  namespace "admin" do
    get "pages/home"
    get "pages/help"

    resources :mobile_services
    resources :service_packages
    resources :package_memberships, :only => [:create, :update, :destroy]
    resources :users

    match "login" => "user_sessions#new", :as => :login
    match "logout" => "user_sessions#destroy", :as => :logout

    root :to => 'pages#home'
    match "/:unknown" => redirect('/admin/pages/home')
  end

  # NOTE: this has to go after all the namespace definitions or else the name space roots will match this route
  match "/:urltitle" => "adaptive#reroute", :as => :urltitle, :via=>:get
  match "/force/:urltitle" => "adaptive#reroute", :as => :urltitle, :via=>:get

  #root :to => 'service_packages', :action=>'show', :id=>'home'

end

app/models/service_package.rb
require 'unique_urltitle_validator'

class ServicePackage < ActiveRecord::Base

  validates :title, :presence => true,
                    :length => { :minimum => 1 }, 
                    :uniqueness => true, 
                    :format => { :with => /[A-Za-z0-9\-\'\"\+\.\!\?\@\$\#\%\&\=\,\: ]+/ }

  validates :urltitle,  :presence => true,
                        :length => { :minimum => 1, :maximum => 32 }, 
                        :uniqueness => true,
                        :format => { :with => /[A-Za-z0-9\-\_]+/ },
                        :unique_urltitle => true

  has_many :package_items, :dependent => :destroy, :class_name => "PackageMembership", :order=>"package_memberships.ordering" # contains

  has_many :package_memberships, :dependent => :destroy, :as => :package_item # contained in
  
  has_attached_file :icon,
    :path => ":rails_root/public/data/:attachment_:class/:id/:style_:basename.:extension",
    :url => "/data/:attachment_:class/:id/:style_:basename.:extension",
    :styles => {
                :base     => "57x57#",
                :x2       => "114x114#",
                :small16  => "16x16#",
                :small    => "29x29#",
                :small50  => "50x50#",
                :x2small  => "58x58#",
                :px72     => "72x72#"
              }

end

app/controllers/admin/service_packages_controller.rb
class Admin::ServicePackagesController < Admin::AdminController

  @@page_title_base = "Admin : Package"
  
  def index
    @service_packages = ServicePackage.all
    @page_title = @@page_title_base+"s"
  end


  def show
    @service_package = ServicePackage.find(params[:id])
    @page_title = @@page_title_base+" : "+@service_package.title
  end


  def new
    @service_package = ServicePackage.new
    @page_title = @@page_title_base+" : New"
  end


  def edit
    @service_package = ServicePackage.find(params[:id])
    @page_title = @@page_title_base+" : Edit "+@service_package.title
    @mobile_services = MobileService.all
    @all_service_packages = ServicePackage.all    
  end


  def create
    @service_package = ServicePackage.new(params[:service_package])
    @service_package.is_live = false    
    if @service_package.save
      redirect_to(admin_service_package_url(@service_package), :notice => 'Package was successfully created.')
    else
      render "new"
    end
  end


  def update
    @service_package = ServicePackage.find(params[:id])
    @mobile_services = MobileService.all
    if @service_package.update_attributes(params[:service_package])
      redirect_to(admin_service_package_url(@service_package), :notice => 'Package was successfully updated.')
    else
      render "edit"
    end
  end


  def destroy
    @service_package = ServicePackage.find(params[:id])
    @service_package.destroy
    redirect_to(admin_service_packages_url)
  end
  
end

app/controllers/service_packages_controller.rb
class ServicePackagesController < ApplicationController

  def index
    #@service_packages = ServicePackage.where(:is_live=>true,:is_restricted=>false)
    #@page_title = "All Apps"
    redirect_to :controller=>"service_packages", :action=>"show", :id=>'home'
  end

  def show
    if (params[:id].to_s.match /\A\d+\Z/)
      @service_package = ServicePackage.find(params[:id])
    else
      @service_package = ServicePackage.find_by_urltitle(params[:id])
    end
    @page_title = @service_package.title

    if (@service_package.is_live)
      process_feed_package_items(@service_package.package_items)
    else
      redirect_to :controller=>"service_packages", :action=>"show", :id=>'home'
    end
  end

end

app/helpers/admin/service_packages_helper.rb
module Admin::ServicePackagesHelper

end

app/helpers/service_packages_helper.rb
module ServicePackagesHelper
end

app/views/admin/service_packages/_form_contents.html.erb
  <% if @service_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_package.errors.count, "error") %> prohibited this service_package from being saved:</h2>

      <ul>
      <% @service_package.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %>
    <div class="form_input"><%= f.text_field :title %></div>
  </div>
  <div class="field">
    <%= f.label :urltitle %>
    <div class="form_input">http://<%=@servername%>/<%= f.text_field :urltitle %></div>
  </div>

  <div class="field">
    <%= f.label :full_site_url %>
    <div class="form_input"><%= f.text_field :full_site_url %> <span class="commentary">(this is optional - it is used to generate a link to a full / desktop page that corresponds to this item)</span></div>
  </div>

  <div class="field">
    <%= f.label 'Icon' %>
    <div class="form_input"><%= f.file_field :icon, :class=>"icon_input" %><% if @service_package.icon.exists? then %>
      <%= image_tag @service_package.icon.url(:small), :class=>"icon_view" %>
    <% end %></div>
  </div>
  <div class="field">
    <%= f.label :description %>
    <div class="form_input"><%= f.text_area :description , :rows => 4%></div>
  </div>

  <div class="field">
    <%= f.label :flag_show_description %>
    <div class="form_input"><%= f.check_box :flag_show_description, {:class=>"flag_show_description_checkbox"} %></div>
  </div>
    
  <div class="field">
    <%= f.label :display_style %>
    <div class="form_input"><%= f.select :display_style, [['list','list'],['grid','grid']] %></div>
  </div>
  
  <div class="field">
    <%= f.label :flag_show_root_link %>
    <div class="form_input"><%= f.check_box :flag_show_root_link, {:class=>"flag_show_root_link_checkbox"} %></div>
  </div>
  
  <div class="field">
    <%= f.label :is_restricted %>
    <div class="form_input"><%= f.check_box :is_restricted, {:class=>"is_restricted_checkbox"} %></div>
  </div>

  <% if controller.action_name != 'new'%>
  <div class="field">
    <%= f.label :is_live %>
    <div class="form_input"><%= f.check_box :is_live, {:class=>"is_live_checkbox"} %></div>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

app/views/admin/service_packages/edit.html.erb
<script type="text/javascript">
$(document).ready(function(){


  function stringSpect(o)
  {
    var res="";
    for (var p in o) {
      res += p+" = "+o[p]+"\n";
    }
    return res;
  }

  $(".services_in_package  .add_button").hide();
  $(".available_services  .remove_button").hide();

  $(".services_in_package ul li").hover(
    function () {
      $(this).addClass("item_hovering");
    },
    function () {
      $(this).removeClass("item_hovering");
    }
  );
  $(".available_services ul li").hover(
    function () {
      $(this).removeClass("item_not_hovering");
      $(this).addClass("item_hovering");
    },
    function () {
      $(this).removeClass("item_hovering");
      $(this).addClass("item_not_hovering");
    }
  );


  $(".services_in_package > ul").sortable({
    update: function(event, ui) { 
      var elt = $("#"+ui.item[0].id);
      //alert("sortable update on "+elt.attr("for_item")+" in "+elt.attr("for_package"));
      //alert("new list is "+stringSpect( $.map(elt.parent().children(),function(e,i){ return $("#"+e.id).attr("for_item"); }) ));
      //alert("prev is "+elt.prev().attr("for_item"));
      
      elt.parent().children().each( function(idx,e) {
        ejq = $("#"+e.id);

        var save_url = '/admin/package_memberships/'+ejq.attr("as");
        $.ajax(
          {
            url: save_url,
            type: 'PUT',
            data: {action: 'update',
                   id: ejq.attr("as"),
                   new_idx: idx},
            success:function(data, textStatus) 
              {
                //alert("save successful");
              },
            error:function(request, textStatus, errorThrown)
              {
                //alert("could not save the new ordering: "+errorThrown);
              }
          });

      } );
      
      
    }
  });

  var no_service_item = "<li>No items</li>";

  $(".add_button").click(
    function()
      {
        var cached_this = this;
        $.ajax(
          {
            url: '<%=admin_package_memberships_path%>',
            type: 'POST',
            data: {action: 'create',
                   item: $(cached_this).parent().attr("for_item"), 
                   package: <%=@service_package.id.to_s%>,
                   item_type: $(cached_this).parent().attr("item_type")},
            success:function(data, textStatus) 
              {
                $(".services_in_package ul li:contains('No items')").remove();
                $(".services_in_package ul").append($(cached_this).parent().detach());
                $(cached_this).parent().find(".button").toggle();
                $(cached_this).parent().attr("as",data);
                if ($(".available_services ul li").length == 0) { 
                  $(".available_services ul").append(no_service_item);
                }          
              },
            error:function(request, textStatus, errorThrown)
              {
                alert("could not put that service in this package: "+errorThrown);
              }
          });
      });


  $(".remove_button").click(
    function()
      {
        var cached_this = this;
        $.ajax(
          {
            url: '/admin/package_memberships/'+$(cached_this).parent().attr("as"),
            type: 'DELETE',
            data: {action: 'destroy',
                   id: $(this).parent().attr("as")},
            success:function(data, textStatus) 
              {
                $(cached_this).parent().attr("as","0");
                $(".available_services ul li:contains('No items')").remove();
                $(".available_services ul").append($(cached_this).parent().detach());
                $(cached_this).parent().find(".button").toggle();
                if ($(".services_in_package ul li").length == 0) { 
                  $(".services_in_package ul").append(no_service_item);
                }
              },
            error:function(request, textStatus, errorThrown)
              {
                alert("could not remove that service from this package: "+request.toString());
              }
          });
      });

});
</script>

<div class="left_col package_info">
<%= form_for(@service_package,
             :html => { :multipart => true },
             :url => admin_service_package_path(@service_package) ) do |f| %>
<%= render 'form_contents', :f => f %>
<% end %>
</div>

<div class="right_col mobile_service_chooser">
  <div class="left_col services_in_package">
    <h2>Items In Package</h2>
      <ul>
    <%if @service_package.package_items.empty?%>
        <li>No items</li>
    <%else%>
      <% @service_package.package_items.each do |pi| 
        ms = pi.package_item %>
        <%=admin_item(pi.package_item, @service_package, pi, ordering_handle+add_button+remove_button+"<div class=\"package_container\">".html_safe,"</div>".html_safe)%>
      <%end%>
    <%end%>
      </ul>
  </div>

  <div class="right_col available_services">
    <h2>Items Available</h2>
    <%if @mobile_services.empty?%>
      <p>No items</p>
    <%else%>
      <ul>
        <% ((@mobile_services + @all_service_packages) - ([@service_package]) - (@service_package.package_items.collect {|pi| pi.package_item })).each do |ms| %>
          <%=admin_item(ms, @service_package, nil, ordering_handle+add_button+remove_button+"<div class=\"package_container\">".html_safe,"</div>".html_safe)%>
        <%end%>
      </ul>
    <%end%>
  </div>

</div>




<br clear="all"/>

<%= link_to 'Show', admin_service_package_path(@service_package) %> |
<%= link_to 'All Packages', admin_service_packages_path %>

<br clear="all"/>

app/views/admin/service_packages/index.html.erb
<h3><%= link_to 'Make a new Package', new_admin_service_package_path %></h3>


<table class="index_lister">

<% @service_packages.each do |service_package| %>
  <tr>  
    <td<%= ((service_package.is_live)?' title="live"':' class="not_live" title="not live"').html_safe %>><%= ((service_package.is_live)?(image_tag "admin/live.png"):(image_tag "admin/not_live.png")) %></td>
    <td><% if service_package.icon.exists? then %>
      <%= image_tag service_package.icon.url(:base) %>
    <% else %>
      NO ICON! (should never be seen!)
    <% end %></td>
    <td><%= service_package.title %></td>
    <td class="first_action" title="see details"><%= link_to (image_tag "admin/information.png"), admin_service_package_path(service_package) %></td>
    <td title="edit"><%= link_to (image_tag "admin/pencil.png"), edit_admin_service_package_path(service_package) %></td>
    <td title="delete"><%= link_to (image_tag "admin/delete.png"), admin_service_package_path(service_package), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/admin/service_packages/new.html.erb
<%= form_for(@service_package,
             :html => { :multipart => true },
             :url => admin_service_packages_path ) do |f| %>
<%= render 'form_contents', :f => f %>
<% end %>

<%= link_to 'Cancel', admin_service_packages_path %>

app/views/admin/service_packages/show.html.erb
<p id="notice"><%= notice %></p>

<div class="left_col">
  <div class="field">
    <label><b>Title:</b></label>
    <div class="value"><%= @service_package.title %></div>
  </div>
  <div class="field">
    <label><b>URL Title:</b></label>
    <div class="value"><i>http://<%=@servername%>/</i><%= @service_package.urltitle %></div>
  </div>
  <div class="field">
    <label><b>Full Site URL:</b></label>
    <div class="value"><%= @service_package.full_site_url %></div>
  </div>
  <div class="field">
    <label><b>Icon:</b></label>
    <div class="value"><% if @service_package.icon.exists? then %>
      <%= image_tag @service_package.icon.url(:small) %>
    <% else %>
      NO ICON! (should never be seen!)
    <% end %></div>
  </div>
  <div class="field">
    <label><b>Description:</b></label>
    <div class="value"><%= @service_package.description %></div>
    <br/><br/>
  </div>
  <div class="field">
    <label><b>Shows Description:</b></label>
    <div class="value"><%= @service_package.flag_show_description %></div>
  </div>
  <div class="field">
    <label><b>Display Style:</b></label>
    <div class="value"><%= @service_package.display_style %></div>
  </div>
  <div class="field">
    <label><b>Shows Root:</b></label>
    <div class="value"><%= @service_package.flag_show_root_link %></div>
  </div>
  <div class="field">
    <label><b>Restricted:</b></label>
    <div class="value"><%= @service_package.is_restricted %></div>
  </div>
  <div class="field">
    <label><b>Live:</b></label>
    <div class="value"><%= @service_package.is_live %></div>
  </div>
</div>

<div class="right_col">
  <div class="mobile_service_list">
   <b>Includes:</b>
   <ul>
   <% if (@service_package.package_items.empty?) %>
    <li>None</li>
   <% else %>
       <% @service_package.package_items.each do |pm| %>
          <%=admin_item(pm.package_item,@service_package,pm,"<div class=\"package_container\">","</div>")%>
    <% end
     end %>
   </ul>
  </div>
</div>

<br clear="all"/>
<%= link_to 'Edit', edit_admin_service_package_path(@service_package) %> |
<%= link_to 'All Packages', admin_service_packages_path %>