config/routes.rb
Mpf::Application.routes.draw do

  secure_protocol = "https"
  if (Rails.env.development? or Rails.env.test?)
    secure_protocol = "http"
  end  

  resources :mobile_services, :only => [:index, :show]
  resources :service_packages, :only => [:index, :show]

  # match "/auth/ldap/callback" => "admin/user_sessions#create", :constraints => { :protocol => secure_protocol }
  # phusion passenger has issues matching a route with a protocol constraint, so using below instead of above
  match "/auth/ldap/callback" => "admin/user_sessions#create"
  match "/auth/failure" => redirect("/admin/login"), :notice => "login failed"
  
  namespace "admin" do
    get "pages/home"
    get "pages/help"

    resources :mobile_services
    resources :service_packages
    resources :package_memberships, :only => [:create, :update, :destroy]
    resources :users

    match "login" => "user_sessions#new", :as => :login
    match "logout" => "user_sessions#destroy", :as => :logout

    root :to => 'pages#home'
    match "/:unknown" => redirect('/admin/pages/home')
  end

  # NOTE: this has to go after all the namespace definitions or else the name space roots will match this route
  match "/:urltitle" => "adaptive#reroute", :as => :urltitle, :via=>:get
  match "/force/:urltitle" => "adaptive#reroute", :as => :urltitle, :via=>:get

  #root :to => 'service_packages', :action=>'show', :id=>'home'

end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
  <title><%=@page_title || "Williams Mobile Admin"%></title>
  <%= stylesheet_link_tag    "admin/application" %>
  <%= javascript_include_tag "admin/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<script type="text/javascript">
$(document).ready(function(){
  $(".button").hover(button_over, button_out);
  function button_over(evt)
  {
    $(this).css("cursor", "pointer");
  }
  function button_out(evt)
  {
  }
});
</script>

<div class="admin_nav">
 <ul>
  <li><%= link_to 'Admin Home', admin_pages_home_path %></li>
  <li><%= link_to 'Services', admin_mobile_services_path %></li>
  <li><%= link_to 'Packages', admin_service_packages_path %></li>
  <li><%= link_to 'Users', admin_users_path %></li>
  <li><%= link_to 'Help', admin_pages_help_path %></li>
  <li class="logout_item"><%= link_to 'Logout', admin_logout_path %></li>
 </ul>
</div>

<h1><%=@page_title%></h1>

<%= yield %>

</body>
</html>