config/routes.rb
Mpf::Application.routes.draw do

  secure_protocol = "https"
  if (Rails.env.development? or Rails.env.test?)
    secure_protocol = "http"
  end  

  resources :mobile_services, :only => [:index, :show]
  resources :service_packages, :only => [:index, :show]

  # match "/auth/ldap/callback" => "admin/user_sessions#create", :constraints => { :protocol => secure_protocol }
  # phusion passenger has issues matching a route with a protocol constraint, so using below instead of above
  match "/auth/ldap/callback" => "admin/user_sessions#create"
  match "/auth/failure" => redirect("/admin/login"), :notice => "login failed"
  
  namespace "admin" do
    get "pages/home"
    get "pages/help"

    resources :mobile_services
    resources :service_packages
    resources :package_memberships, :only => [:create, :update, :destroy]
    resources :users

    match "login" => "user_sessions#new", :as => :login
    match "logout" => "user_sessions#destroy", :as => :logout

    root :to => 'pages#home'
    match "/:unknown" => redirect('/admin/pages/home')
  end

  # NOTE: this has to go after all the namespace definitions or else the name space roots will match this route
  match "/:urltitle" => "adaptive#reroute", :as => :urltitle, :via=>:get
  match "/force/:urltitle" => "adaptive#reroute", :as => :urltitle, :via=>:get

  #root :to => 'service_packages', :action=>'show', :id=>'home'

end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  @@page_title_base = "Admin : User"
  
  def index
    @page_title = @@page_title_base+"s"
    @users = User.all
  end


  def show
    @user = User.find(params[:id])
    @page_title = @@page_title_base+" : "+@user.first_name+" "+@user.last_name
  end


  def new
    @user = User.new
    @page_title = @@page_title_base+" : New"
  end


  def edit
    @user = User.find(params[:id])
    @page_title = @@page_title_base+" : Edit "+@user.first_name+" "+@user.last_name
  end


  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(admin_user_url(@user), :notice => 'User was successfully created.')
    else
      render "new"
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to(admin_user_url(@user), :notice => 'User was successfully updated.')
    else
      render "edit"
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(admin_users_url)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form_contents.html.erb
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <div class="form_input"><%= f.text_field :username %></div>
  </div>
  <div class="field">
    <%= f.label :first_name %>
    <div class="form_input"><%= f.text_field :first_name %></div>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <div class="form_input"><%= f.text_field :last_name %></div>
  </div>
  <div class="field">
    <%= f.label :role %>
    <div class="form_input"><%= f.select(:role, options_for_select([["none","none"],["admin","admin"]],(@user.role? ? @user.role : "none")))%></div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

app/views/admin/users/edit.html.erb
<%= form_for(@user, :url => admin_user_path(@user) ) do |f| %>
<%= render 'form_contents', :f => f %>
<% end %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Cancel', admin_users_path %>

app/views/admin/users/index.html.erb
<table class="index_lister">
  <tr>
    <th>Username</th>
    <th>First</th>
    <th>Last</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.role %></td>
    <td class="first_action"><%= link_to (image_tag "admin/information.png"), admin_user_path(user) %></td>
    <td><%= link_to (image_tag "admin/pencil.png"), edit_admin_user_path(user) %></td>
    <td><%= link_to (image_tag "admin/delete.png"), admin_user_path(user), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<%= form_for(@user, :url => admin_users_path ) do |f| %>
<%= render 'form_contents', :f => f %>
<% end %>

<%= link_to 'Cancel', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <div class="field">
    <label><b>Username:</b></label>
    <div class="value"><%= @user.username %></div>
  </div>
  <div class="field">
    <label><b>First Name:</b></label>
    <div class="value"><%= @user.first_name %></div>
  </div>
  <div class="field">
    <label><b>Last Name:</b></label>
    <div class="value"><%= @user.last_name %></div>
  </div>
  <div class="field">
    <label><b>Role:</b></label>
    <div class="value"><%= @user.role %></div>
  </div>
</div>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'All Users', admin_users_path %>